### ISSUE TITLE
maxAge

### ISSUE THREAD

**Issue by sveinburne** [meloncholy/vid-streamer#26]
What does this setting option states for? Can't find anything in the doc !

**Comment by meloncholy** [comment]
It tells the browser for how long it should cache the response, which should hopefully save you a bit of bandwidth if your files don't change that often. [HTTP caching page from Google](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/http-caching?hl=en)

You're right, though, that I should really update the docs. :smile:

**Comment by sveinburne** [comment]
Thanks a lot ! 
okay it's a http header field ! Should also report the unit is seconds
